management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8091
  tomcat:
    threads:
      max: 1000

spring:
  application:
    name: footprint-service
  profiles:
    active: dev
  cloud:
    nacos:
      username: nacos
      password: 1-6123
      discovery:
        server-addr: 114.215.198.238:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialization-mode: always
    schema: classpath:schema.sql
    data: classpath:testdata.sql
    druid:
      #初始化时建立物理连接的个数
      initial-size: 3
      #最小连接池数量
      min-idle: 3
      #最大连接池数量
      max-active: 100
      #获取连接时最大等待时间
      max-wait: 60000
      filter:
        stat:
          #是否开启慢sql查询监控
          log-slow-sql: true
          #慢SQL执行时间
          slow-sql-millis: 100
      validation-query: select 1
    sql-script-encoding: UTF-8

mybatis:
  #po对象的包
  type-aliases-package: cn.edu.xmu.footprint.model
  #mapper.xml所在的位置
  mapper-locations: classpath*:cn.edu.xmu.footprint.mapper/*.xml
  #自动将SQL中查出来的带下划线的字段，转换为驼峰标志，再去匹配类中的属性
  configuration:
    #输出产生的SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

footprintservice:
  #是否对数据库中的未初始化的数据初始化
  initialization: false
  #分布式锁失效时间（秒）
  lockerExpireTime: 30
  #图片存储位置
  imglocation: ./img
  user:
    # user的权限字在Redis中失效秒数
    expiretime: 600
  role:
    # role的权限字在Redis中失效秒数
    expiretime: 600
  login:
    #是否允许重复登录
    multiply: false
    #jwt过期的时间(秒)
    jwtExpire: 3600


#pagehelper分页插件配置
pagehelper:
  helper-dialect: mysql

dubbo:
  registry:
    address: nacos://114.215.198.238:8848
  cloud:
    subscribed-services: spring-cloud-alibaba-dubbo-server
  protocols:
    dubbo:
      port: 18890
  consumer:
    timeout: 60000
    check: false





