package cn.edu.xmu.favorite.mapper;

import cn.edu.xmu.favorite.model.po.FavoritePo;
import cn.edu.xmu.favorite.model.po.FavoritePoExample;
import java.util.List;

public interface FavoritePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int insert(FavoritePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int insertSelective(FavoritePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    List<FavoritePo> selectByExample(FavoritePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    FavoritePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FavoritePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favourite_goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FavoritePo record);
}