package cn.edu.xmu.address.mapper;

import cn.edu.xmu.address.model.po.AddressPo;

public interface AddressPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    int insert(AddressPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    int insertSelective(AddressPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    AddressPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AddressPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_address
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AddressPo record);
}