
spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    url: jdbc:mysql://114.215.198.238:4502/oomall_other?serverTimezone=GMT%2B8
    username: root
    password: 123456789
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*
#  redis:
#    # Redis服务器地址
#    host: 114.215.198.238
#    # Redis服务器连接端口
#    port: 4506
#    # Redis服务器连接密码
#    password: 123456

  redis:
    # Redis服务器地址
    host: 114.215.198.238
    # Redis服务器连接端口
    port: 4506
    # Redis服务器连接密码
    # Redis数据库索引（默认为0）
    password: 123456
    database: 0
    #连接池最大连接数（使用负值表示没有限制）
    lettuce:
      pool:
        max-active: 100
        # 连接池中的最大空闲连接
        max-idle: 100
        # 连接池中的最小空闲连接
        min-idle: 0
        #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
    # 连接超时时间（毫秒）
    timeout: 5000