
spring:
  boot:
    admin:
      client:
        url: http://localhost:8081
  datasource:
    url: jdbc:mysql://114.215.198.238:4502/oomall_inner?serverTimezone=GMT%2B8
    username: root
    password: 123456789
#    url: jdbc:mysql://172.16.0.139:3306/oomall_other?serverTimezone=GMT%2B8
#    username: root
#    password: 123456789
    druid:
      stat-view-servlet:
        login-username: admin
        login-password: 123456
        enabled: true
        url-pattern: /druid/*