package cn.edu.xmu.footprint.mapper;

import cn.edu.xmu.footprint.model.po.FootPrintPo;
import cn.edu.xmu.footprint.model.po.FootPrintPoExample;
import java.util.List;

public interface FootPrintPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    int insert(FootPrintPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    int insertSelective(FootPrintPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    List<FootPrintPo> selectByExample(FootPrintPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    FootPrintPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FootPrintPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FootPrintPo record);
}