package cn.edu.xmu.footprint.mapper;

import cn.edu.xmu.footprint.model.po.FootprintPo;
import cn.edu.xmu.footprint.model.po.FootprintPoExample;
import java.util.List;

public interface FootprintPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    int insert(FootprintPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    int insertSelective(FootprintPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    List<FootprintPo> selectByExample(FootprintPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    FootprintPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FootprintPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table foot_print
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FootprintPo record);
}