package cn.edu.xmu.advertisement.mapper;

import cn.edu.xmu.advertisement.model.po.AdvertisementPo;
import cn.edu.xmu.advertisement.model.po.AdvertisementPoExample;
import java.util.List;

public interface AdvertisementPoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_advertisement
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_advertisement
     *
     * @mbg.generated
     */
    int insert(AdvertisementPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_advertisement
     *
     * @mbg.generated
     */
    int insertSelective(AdvertisementPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_advertisement
     *
     * @mbg.generated
     */
    List<AdvertisementPo> selectByExample(AdvertisementPoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_advertisement
     *
     * @mbg.generated
     */
    AdvertisementPo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_advertisement
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AdvertisementPo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table other_advertisement
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AdvertisementPo record);
}