package cn.edu.xmu.aftersales.mapper;

import cn.edu.xmu.aftersales.model.po.AftersaleServicePo;
import cn.edu.xmu.aftersales.model.po.AftersaleServicePoExample;
import java.util.List;

public interface AftersaleServicePoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    int insert(AftersaleServicePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    int insertSelective(AftersaleServicePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    List<AftersaleServicePo> selectByExample(AftersaleServicePoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    AftersaleServicePo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(AftersaleServicePo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aftersale_service
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(AftersaleServicePo record);
}